services:
  db:
    restart: unless-stopped
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=upstat
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  api:
    restart: unless-stopped
    container_name: upstat-backend
    image: upstat-backend:dev
    environment:
      - DB_TYPE=postgres
      - POSTGRES_DSN=postgres://postgres:postgres@db:5432/upstat?sslmode=disable
      - JWT_SECRET_KEY=asdfjaskljdaq123#!@810248)_+12
    depends_on:
      db:
        condition: service_healthy
    ports: 
     - "8001:8000"

  web:
    restart: unless-stopped
    image: upstat-frontend:dev
    ports:
      - "3000:3000"
    depends_on:
      - api
      - db

volumes:
  postgres_data:
