apiVersion: v1
kind: Service
metadata:
  name: upstat-frontend
spec:
  type: NodePort
  selector:
    app: upstat-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30002
    name: upstat-frontend-port
